### PR TITLE
Initial semver tag; update README.md

### PR DESCRIPTION
**Pull request by backspaces**
This adds a semver version (v1.0.0) and updates the readme file

### CODE REVIEW

**Comment by kenrussell** [comment]
Is there supposed to be a new file in this pull request? Only README.md is modified. Don't forget to "git add" new files.

**Comment by backspaces** [comment]
​Tags are weird.  They apparently aren't actually "files" or similar in a
git repo. Metadata. So it appears to me that I have to modify a file in the
repo to have the new v1.0.0 ​tag be assigned to the repo. Thus the change
to README.

You asked for a PR, so I went ahead and followed
    https://www.khronos.org/webgl/wiki/Using_Github_To_Contribute
​Clone, branch (semver), edit README, tag it, push etc.
    https://help.github.com/articles/creating-a-pull-request/

So if you look at the PR, you can see that the semver branch has 1 release,
the v1.0.0 tag. That's where the magic occurs. If you clone my repo to your
computer, you should be able to type "git tag" and it will show v1.0.0
while that won't happen with a clone of the Khronos repo.  I think!

To tell the truth, I have near zero git-fu, so had to do a lot of reading.
I turns out you can simply add a tag to the existing Khronos repo via:
    https://help.github.com/articles/creating-releases/
You don't really need a PR, you can simply add the tag directly to the
github repo. Clone it to your computer and "git tag" should show the tag.

Fine with me if you just do that yourself, the README edit was only to get
github to accept a push to my branch for the PR! Odd.

   -- Owen

**Comment by kenrussell** [comment]
I see. Thanks for the clarification. I confirmed that cloning your repo makes that tag show up. Let's see if merging your pull request does the same. Thanks for this contribution.

**Comment by kenrussell** [comment]
Unfortunately that didn't work. Let me try via the command line.

**Comment by kenrussell** [comment]
I've pushed a v1.0.0 tag to the KhronosGroup/WebGLDeveloperTools repository, which you can see in the GUI. Please tell me whether it looks like this suits your needs. I'm not 100% sure how to make this show up in forks of the repository. It doesn't look like it's possible to create tags via pull requests.

**Pull request merged**
